version: "3"
services:
  nodejs:
    container_name: nodejs
    build: .
    ports:
      - 9000:9000
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - mynetwork
    mem_limit: 1g

networks:
  mynetwork:
    driver: bridge
