version: "3"
services:
  server:
    container_name: server
    build: .
    ports:
      - 9000:9000
    depends_on:
      - redis-server
    networks:
      - mynetwork

  redis-server:
    container_name: redis-server
    image: redis
    ports:
      - 6379:6379
    networks:
      - mynetwork
    mem_limit: 100m

networks:
  mynetwork:
    driver: bridge
